# Basic meta
project: "ddpm-cifar10"
run_name: "cifar10_ddpm_fp32"

wandb:
  enabled: true
  mode: online
  tags: ["cifar10", "ddpm", "fp32"]

compute:
  enable_tf32: true

data:
  dataset: "cifar10"
  image_size: 32
  batch_size: 512
  num_workers: 8
  augment: true         # RandomCrop(32,pad=4) + Flip

model:
  dim: 64           # try 96 or 128 if GPU allows
  dim_mults: [1, 2, 2, 4]  # 32->16->8->4
  channels: 3           # CIFAR-10 is RGB
  attn_heads: 4
  attn_dim_head: 28
  dropout: 0.05
  self_condition: false
  learned_variance: false
  outer_attn: true

diffusion:
  T: 300
  beta_schedule: cosine
  objective: pred_noise     
  sampling_steps: 300      
  eta: 0.0
  self_condition: false
  clamp_x0: true
  sample_every: 50000
  sample_n: 64

opt:
  lr: 1e-4
  betas: [0.9, 0.99]
  grad_clip: 1.0
  weight_decay: 0.0

train:
  max_steps: 100000        
  log_every: 200
  grad_accum: 1
  ckpt_dir: "./ckpt_cifar10"

ema:
  enabled: false
  decay: 0.995
  update_every: 10

metrics:
  global_norm_every: 100000
  enable_fid: false         # off for now
  enable_is: false

viz:
  enable_forward_traj: true
  forward_every_steps: 50000
  # Either give explicit t-values or use stride:
  # forward_t_values: [0, 50, 100, 200, 400, 600, 800, 999]
  forward_record_every: 20

  enable_reverse_traj: true
  reverse_every_steps: 50000
  reverse_record_every: 20

  forward_batch_n: 16
  reverse_batch_n: 16
  video_fps: 16
